apiVersion : v1
kind : Service
metadata :
  name : {{ .Release.Name }} - service
spec :
  type : {{ .Values.service.type }}
  ports :
  - port : {{ .Values.service.port }}
    targetPort : 3000
    nodePort : 30001
  selector :
    app : todo-api
